using System.Linq;
using System.IO;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.AI;
using Unity.AI.Navigation;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;
using UnityEngine.SceneManagement;
using ZombiePrototype;

namespace ZombiePrototype.Editor
{
    public static class ZombieDemoSceneBuilder
    {
        private const string ScenePath = "Assets/Scenes/Zombie_Demo.unity";
        private const string BuildMarkerPath = "Assets/Scenes/Zombie_Demo.autobuilt";

        [InitializeOnLoadMethod]
        private static void AutoBuildOnce()
        {
            EditorApplication.delayCall += () =>
            {
                if (Application.isPlaying || EditorApplication.isCompiling)
                {
                    return;
                }

                FixMaterialsForUrp();

                if (File.Exists(BuildMarkerPath))
                {
                    return;
                }

                Build();
                File.WriteAllText(BuildMarkerPath, "Generated by ZombieDemoSceneBuilder. Delete this file to auto-rebuild on next Unity launch.");
                AssetDatabase.ImportAsset(BuildMarkerPath);
            };
        }

        [MenuItem("Tools/Zombie Prototype/Rebuild Demo Scene")]
        public static void Build()
        {
            FixMaterialsForUrp();
            Scene scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);

            CreateLighting();
            CreateArena();
            CreateNavMesh();
            FirstPersonPlayer player = CreatePlayer();
            CreateGameSystems(player);

            EditorSceneManager.SaveScene(scene, ScenePath);
            AddSceneToBuildSettings();
            AssetDatabase.SaveAssets();
            Debug.Log($"Zombie demo scene rebuilt at {ScenePath}");
        }

        [MenuItem("Tools/Zombie Prototype/Fix PolygonZombies Materials For URP")]
        public static void FixMaterialsForUrp()
        {
            Shader urpLit = Shader.Find("Universal Render Pipeline/Lit");
            Shader zombieShader = Shader.Find("SyntyStudios/Zombies");

            foreach (string guid in AssetDatabase.FindAssets("t:Material", new[] { "Assets/PolygonZombies" }))
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                Material material = AssetDatabase.LoadAssetAtPath<Material>(path);
                if (material == null)
                {
                    continue;
                }

                if (material.name.StartsWith("PolygonZombie_Texture") && zombieShader != null)
                {
                    Texture texture = material.HasProperty("_Texture") ? material.GetTexture("_Texture") : material.GetTexture("_MainTex");
                    material.shader = zombieShader;
                    if (texture != null)
                    {
                        material.SetTexture("_Texture", texture);
                    }
                }
                else if (urpLit != null)
                {
                    Color color = material.HasProperty("_Color") ? material.GetColor("_Color") : Color.gray;
                    Texture texture = material.HasProperty("_MainTex") ? material.GetTexture("_MainTex") : null;
                    material.shader = urpLit;
                    material.SetColor("_BaseColor", color);
                    if (texture != null)
                    {
                        material.SetTexture("_BaseMap", texture);
                    }
                }

                EditorUtility.SetDirty(material);
            }

            AssetDatabase.SaveAssets();
        }

        private static void CreateLighting()
        {
            RenderSettings.ambientMode = AmbientMode.Flat;
            RenderSettings.ambientLight = new Color(0.32f, 0.36f, 0.39f);
            RenderSettings.fog = true;
            RenderSettings.fogColor = new Color(0.2f, 0.22f, 0.24f);
            RenderSettings.fogDensity = 0.018f;

            GameObject lightObject = new GameObject("Directional Light");
            Light light = lightObject.AddComponent<Light>();
            light.type = LightType.Directional;
            light.intensity = 1.7f;
            light.shadows = LightShadows.Soft;
            lightObject.transform.rotation = Quaternion.Euler(52f, -35f, 0f);
        }

        private static void CreateArena()
        {
            Material groundMaterial = AssetDatabase.LoadAssetAtPath<Material>("Assets/PolygonZombies/Materials/Alts/Demo_Ground_Mat.mat");

            GameObject ground = GameObject.CreatePrimitive(PrimitiveType.Cube);
            ground.name = "Concrete Arena";
            ground.transform.localScale = new Vector3(60f, 0.35f, 60f);
            ground.transform.position = new Vector3(0f, -0.18f, 0f);
            if (groundMaterial != null)
            {
                ground.GetComponent<Renderer>().sharedMaterial = groundMaterial;
            }

            CreateWall("North Wall", new Vector3(0f, 1.5f, 30f), new Vector3(60f, 3f, 1f));
            CreateWall("South Wall", new Vector3(0f, 1.5f, -30f), new Vector3(60f, 3f, 1f));
            CreateWall("East Wall", new Vector3(30f, 1.5f, 0f), new Vector3(1f, 3f, 60f));
            CreateWall("West Wall", new Vector3(-30f, 1.5f, 0f), new Vector3(1f, 3f, 60f));

            for (int i = 0; i < 10; i++)
            {
                GameObject cover = GameObject.CreatePrimitive(PrimitiveType.Cube);
                cover.name = "Cover Block";
                cover.transform.position = new Vector3(Random.Range(-20f, 20f), 0.75f, Random.Range(-20f, 20f));
                cover.transform.localScale = new Vector3(Random.Range(2f, 4f), 1.5f, Random.Range(2f, 4f));
            }
        }

        private static void CreateNavMesh()
        {
            // NavMeshSurface 是 AI Navigation 包提供的组件。
            // 它的作用是把场景里的地面、墙、箱子等几何体分析一遍，
            // 生成一张“哪些地方可以走、哪些地方不能走”的导航网格。
            //
            // ZombieAI 里的 NavMeshAgent 只会在这张导航网格上移动。
            // 所以当箱子和墙被烘焙进 NavMesh 后，僵尸就不会直接穿过去。
            GameObject navMeshObject = new GameObject("NavMesh Surface");
            NavMeshSurface surface = navMeshObject.AddComponent<NavMeshSurface>();

            // CollectObjects.All 表示收集当前场景里的所有可用几何体。
            // 这里是 Demo 场景，全部收集最简单。
            surface.collectObjects = CollectObjects.All;

            // layerMask = ~0 表示所有 Layer 都参与烘焙。
            surface.layerMask = ~0;

            // RenderMeshes 表示用模型网格来生成 NavMesh。
            // 对当前这些 Cube 地面、墙、障碍物来说很合适。
            surface.useGeometry = NavMeshCollectGeometry.RenderMeshes;
            surface.defaultArea = 0;

            // 立刻在编辑器里烘焙 NavMesh，并把数据保存进场景。
            // 之后运行时僵尸的 NavMeshAgent 就能直接使用。
            surface.BuildNavMesh();
        }

        private static void CreateWall(string name, Vector3 position, Vector3 scale)
        {
            GameObject wall = GameObject.CreatePrimitive(PrimitiveType.Cube);
            wall.name = name;
            wall.transform.position = position;
            wall.transform.localScale = scale;
        }

        private static FirstPersonPlayer CreatePlayer()
        {
            GameObject playerObject = new GameObject("Player");
            playerObject.transform.position = new Vector3(0f, 1.05f, -8f);

            CharacterController controller = playerObject.AddComponent<CharacterController>();
            controller.height = 1.8f;
            controller.radius = 0.34f;
            controller.center = new Vector3(0f, 0.9f, 0f);

            Health health = playerObject.AddComponent<Health>();
            health.ResetHealth(100f);

            FirstPersonPlayer player = playerObject.AddComponent<FirstPersonPlayer>();

            GameObject cameraObject = new GameObject("Main Camera");
            cameraObject.tag = "MainCamera";
            cameraObject.transform.SetParent(playerObject.transform);
            cameraObject.transform.localPosition = new Vector3(0f, 1.62f, 0f);
            Camera camera = cameraObject.AddComponent<Camera>();
            camera.fieldOfView = 72f;
            camera.nearClipPlane = 0.03f;
            cameraObject.AddComponent<UniversalAdditionalCameraData>();
            cameraObject.AddComponent<AudioListener>();

            GameObject weaponObject = new GameObject("Ray Rifle");
            weaponObject.transform.SetParent(cameraObject.transform);
            weaponObject.transform.localPosition = new Vector3(0.34f, -0.28f, 0.58f);
            weaponObject.transform.localRotation = Quaternion.Euler(0f, 0f, 0f);
            CreateWeaponMesh(weaponObject.transform);

            GameObject muzzle = new GameObject("Muzzle");
            muzzle.transform.SetParent(weaponObject.transform);
            muzzle.transform.localPosition = new Vector3(0f, 0.03f, 0.62f);

            LineRenderer tracer = weaponObject.AddComponent<LineRenderer>();
            tracer.positionCount = 2;
            tracer.startWidth = 0.035f;
            tracer.endWidth = 0.005f;
            tracer.material = new Material(Shader.Find("Sprites/Default"));
            tracer.startColor = new Color(1f, 0.86f, 0.25f, 1f);
            tracer.endColor = new Color(1f, 0.1f, 0.05f, 0.1f);
            tracer.enabled = false;

            WeaponRaycaster weapon = weaponObject.AddComponent<WeaponRaycaster>();
            SerializedObject serializedWeapon = new SerializedObject(weapon);
            serializedWeapon.FindProperty("sourceCamera").objectReferenceValue = camera;
            serializedWeapon.FindProperty("muzzle").objectReferenceValue = muzzle.transform;
            serializedWeapon.FindProperty("tracer").objectReferenceValue = tracer;
            serializedWeapon.ApplyModifiedPropertiesWithoutUndo();

            SerializedObject serializedPlayer = new SerializedObject(player);
            serializedPlayer.FindProperty("viewCamera").objectReferenceValue = camera;
            serializedPlayer.ApplyModifiedPropertiesWithoutUndo();

            return player;
        }

        private static void CreateWeaponMesh(Transform parent)
        {
            GameObject body = GameObject.CreatePrimitive(PrimitiveType.Cube);
            body.name = "Rifle Body";
            body.transform.SetParent(parent);
            body.transform.localPosition = Vector3.zero;
            body.transform.localScale = new Vector3(0.22f, 0.16f, 0.72f);
            Object.DestroyImmediate(body.GetComponent<Collider>());

            GameObject barrel = GameObject.CreatePrimitive(PrimitiveType.Cylinder);
            barrel.name = "Barrel";
            barrel.transform.SetParent(parent);
            barrel.transform.localPosition = new Vector3(0f, 0.02f, 0.56f);
            barrel.transform.localRotation = Quaternion.Euler(90f, 0f, 0f);
            barrel.transform.localScale = new Vector3(0.045f, 0.28f, 0.045f);
            Object.DestroyImmediate(barrel.GetComponent<Collider>());
        }

        private static void CreateGameSystems(FirstPersonPlayer player)
        {
            GameObject systems = new GameObject("Game Systems");

            GameManager gameManager = systems.AddComponent<GameManager>();
            SerializedObject serializedManager = new SerializedObject(gameManager);
            serializedManager.FindProperty("player").objectReferenceValue = player;
            serializedManager.ApplyModifiedPropertiesWithoutUndo();

            ZombieSpawner spawner = systems.AddComponent<ZombieSpawner>();
            SerializedObject serializedSpawner = new SerializedObject(spawner);
            serializedSpawner.FindProperty("player").objectReferenceValue = player.transform;

            string[] prefabGuids = AssetDatabase.FindAssets("t:Prefab", new[] { "Assets/PolygonZombies/Prefabs" })
                .Select(AssetDatabase.GUIDToAssetPath)
                .Where(path => path.Contains("/Zombie_"))
                .OrderBy(path => path)
                .Take(10)
                .ToArray();

            serializedSpawner.FindProperty("zombieVisualPrefabs").arraySize = prefabGuids.Length;
            for (int i = 0; i < prefabGuids.Length; i++)
            {
                serializedSpawner.FindProperty("zombieVisualPrefabs").GetArrayElementAtIndex(i).objectReferenceValue =
                    AssetDatabase.LoadAssetAtPath<GameObject>(prefabGuids[i]);
            }

            serializedSpawner.ApplyModifiedPropertiesWithoutUndo();

            ZombieHud hud = systems.AddComponent<ZombieHud>();
            SerializedObject serializedHud = new SerializedObject(hud);
            serializedHud.FindProperty("player").objectReferenceValue = player;
            serializedHud.FindProperty("weapon").objectReferenceValue = player.GetComponentInChildren<WeaponRaycaster>();
            serializedHud.ApplyModifiedPropertiesWithoutUndo();
        }

        private static void AddSceneToBuildSettings()
        {
            EditorBuildSettingsScene[] scenes = EditorBuildSettings.scenes;
            if (scenes.Any(scene => scene.path == ScenePath))
            {
                return;
            }

            EditorBuildSettings.scenes = scenes.Concat(new[] { new EditorBuildSettingsScene(ScenePath, true) }).ToArray();
        }
    }
}
